### ISSUE TITLE
Compilation error on Windows

### ISSUE THREAD

**Issue by relf** [davidMcneil/mnist#10]
Follow-up of [linfa compilation problem](https://github.com/rust-ml/linfa/issues/209) due to mnist 0.5. 
It comes from the use of `cfg!` in [download.rs](https://github.com/davidMcneil/mnist/blob/6b87176c1bf8781dbecf49ce87581d53039b4d26/src/download.rs#L86) which does not remove any code unlike `#[cfg]`, hence the error on Windows.

**Comment by quietlychris** [comment]
I'll try putting together a fix later today, but won't have a Windows machine to build on. Would you mind testing that code for this library and compiling `linfa` with the git repository as a dependency one it's ready?

**Comment by relf** [comment]
@davidMcneil, thank you for merging #11. Do you think you could publish a new version of the crate in the coming weeks? It would be very much appreciated.

**Comment by quietlychris** [comment]
@davidMcneil When you get a chance, would you mind potentially cutting a new update to crates.io now that this fix has been merged? There's a small PR in the [`dfdx`](https://github.com/coreylowman/dfdx/pull/426) library that's currently a bit stuck due to a CI error on Windows that seems to be a result of this. Thanks for your consideration!

Absolutely no pressure, but if you're interested, the Rust-ML group ([GH](https://github.com/rust-ml), [crates.io](https://crates.io/teams/github:rust-ml:wg)) would also be happy to be added as a co-maintainer for this crate in case you find yourself with limited availability in the future.

**Comment by davidMcneil** [comment]
Published https://crates.io/crates/mnist
